### ISSUE TITLE
Problem with getters in a nested module

### ISSUE THREAD

**Issue by dimagimburg** [ktsn/vuex-toast#11]
Hi @ktsn , I really like that simple tool, especially in how it is integrated with vuex, however I face some issue with the getters when wanted to include it as a submodule inside some interface module I created. I guess it has something with the fact that my module is namespaced.

I am providing some context code:
my module is constructed with few separated files (following my projects conventions)

**types.js**
```
export const TYPE_NAME = 'notifications';

export const GETTERS = {
};

export const ACTIONS = {
  showInfoNotification: 'showInfoNotification',
  showSuccessNotification: 'showSuccessNotification',
  showWarningNotification: 'showWarningNotification',
  showErrorNotification: 'showErrorNotification',
};

export const MUTATIONS = {
};

export const TYPES = {
  TYPE_NAME,
  GETTERS,
  ACTIONS,
  MUTATIONS
};
```

**actions.js**
```
import { ACTIONS } from './types'
import { ADD_TOAST_MESSAGE } from 'vuex-toast'

let showNotifications = (dispatch, type, message) => {
  dispatch(ADD_TOAST_MESSAGE, { text: message, type: type, dismissAfter: 4500 });
};

export default {
  [ACTIONS.showInfoNotification]: ({ dispatch }, message) => {
    showNotifications(dispatch, 'info', message);
  },

  [ACTIONS.showSuccessNotification]: ({ dispatch }, message) => {
    showNotifications(dispatch, 'success', message);
  },

  [ACTIONS.showWarningNotification]: ({ dispatch }, message) => {
    showNotifications(dispatch, 'warning', message);
  },

  [ACTIONS.showErrorNotification]: ({ dispatch }, message) => {
    showNotifications(dispatch, 'error', message);
  },

};
```

**index.js**

```
import getters from './getters'
import state from './state'
import actions from './actions'
import mutations from './mutations'

import { createModule as createVueToastModule } from 'vuex-toast'

export default {
  namespaced: true,
  state,
  getters,
  mutations,
  actions,
  modules: {
    toast: {
      ...createVueToastModule()
    }
  }
}
```

the error: 
![toast_error](https://user-images.githubusercontent.com/7847057/36259844-2a7f83e6-1268-11e8-9ea8-64a899690c5d.png)

vuetools screenshot:
![vuetools](https://user-images.githubusercontent.com/7847057/36261663-c84b19c8-126d-11e8-9bf4-08ec6b3b3954.png)

when I tried to manipulate a bit your source code to make it work I finished with editing [this line of code](https://github.com/ktsn/vuex-toast/blob/3a7e23342f2666efe21a426951702cb145370f44/src/Toast.vue#L32). I have basically add my namespace prefix so it looks something like this like this which I really don't like: 
```
messages: `${NOTIFICATIONS_NAMESPACE_PREFIX}toastMessages`
```

How should I use it inside a nested module? should I somehow provide the prefix to the `createModule` constructor or something similar, although the getters are mapped on the Toast component itself?

Thanks a lot!

**Comment by dennisgarrn** [comment]
Hi @dimagimburg,

I had the same problem with namespaced Modules within the Store.

Try following:

```javascript
dispatch(ADD_TOAST_MESSAGE,
  {
    text: message,
    type: type,
    dismissAfter: 4500
  },
  { root: true }
);
```

Documentation: https://vuex.vuejs.org/en/modules.html#accessing-global-assets-in-namespaced-modules

**Comment by ktsn** [comment]
Hi, @dimagimburg 

You can use `<Toast namespace="(your module namespace)" />` to use it under namespaced module since v0.1.3.

**Comment by dimagimburg** [comment]
@ktsn Oh so sorry, missed it in the documentation. I'll use this opportunity to ask more general question about it as you are one of vuex team members, for this kind of issues (namespaced modules) is this the only way to solve it? provide the namespace as a prop? I'm asking because I faced it few times throughout my applications. Thank you so much.

@dennisgarrn thanks for the comment however my issue is a bit different and what @ktsn provided a solution fro this with the namespace prop. thanks.

**Comment by ktsn** [comment]
@dimagimburg 

> you should provide the namespace with a slash in the end of the namespace string

That is actually not needed since it is handled in the Toast component under the hood.
https://github.com/ktsn/vuex-toast/blob/master/src/Toast.vue#L43-L54

> is this the only way to solve it? 

I think we can also provide some component generator function that can receive a namespace string:

```js
function createToast(namespace = '') {
  return {
    // ... Toast component definitiona ...

    computed: mapGetters(namespace, ['toastMessages']
  }
}
```

But it would make the implementation trickier. Passing namespace to prop is simplest solution, I think.
