### ISSUE TITLE
Vuex-toast styling not seem to be  compatible with Nuxt framework ?

### ISSUE THREAD

**Issue by mpatino117** [ktsn/vuex-toast#9]
For some reason the CSS is not appearing, I have to make a separate file and import the styling.

https://nuxtjs.org/

**Comment by SebT** [comment]
I have the same issue and I'm not using nuxt. Importing the Toast component seems not to import the styling with it.

**Comment by ktsn** [comment]
Can you please provide a reproduction?

**Comment by SebT** [comment]
I just followed the instructions from the README. Using `import { Toast } from 'vuex-toast'` in my App.vue component (the toast in rendered at the same level than the router).

And if I don't add `@import '~vuex-toast/dist/vuex-toast.css';` in my `<style lang="scss">`, there is no styling.

**Comment by ktsn** [comment]
Well, it's expected since js and css of vuex-toast is separated. I'll update the docs later.
